{
  imports = [
    ./bash.nix
    ./bat.nix
    ./delta.nix
    ./dircolors.nix
    ./direnv.nix
    ./eza.nix
    ./fd.nix
    ./fzf.nix
    ./gh.nix
    ./ghostty.nix
    ./git.nix
    ./gtk.nix
    ./home.nix
    ./htop.nix
    ./kitty.nix
    ./lazygit.nix
    ./nix-your-shell.nix
    ./nixvim.nix
    ./ripgrep.nix
    ./secrets.nix
    ./spicetify.nix
    ./starship.nix
    ./stylix.nix
    ./tmux.nix
    ./vesktop.nix
    ./yt-dlp.nix
    ./zoxide.nix
    ./zsh.nix
  ];
}
