matrix: ENC[AES256_GCM,data:T7oSUVK73Dfs6wLhisth/TnlQE0AoGAiyN4+P4ywBhOzSDm5HLH7OhEigIJiUlUKBjN01Bs3tP6KeNw=,iv:U9J2QXSlM07CeaVXdH6kEWPvqIVjh6BlHOs+Af38ulI=,tag:C1KpE/ek/+nHc4kRYM8ylA==,type:str]
openclaw-telegram-token: ENC[AES256_GCM,data:UycIsypIDI1RvNT0gnawuEgQGcTHyQJb6LCLmf3ABisxNxmZrsfkHLmZ+9SLVg==,iv:uxoaNQ1QK+D2gb2BE04L7keUk5C0PnUIvl/gMSdpyT8=,tag:/l33uuE8Zu9kQwEIayILMg==,type:str]
openclaw-env: ENC[AES256_GCM,data:IOmfA8hpnfSCg8j2/PcNiWpsH0Gz0sTZFjyhkdkd+UiXtMx/C4FYJq1b+RufXsa1tea6+dgreADM6p6/qMhp6rIK88fFXMjqsSQh8cCTpbQe962vUTYKYqi8TtkJIOm6nO4VceiqTEwzWxtzf9sUUAzoGRJYtnMI6iSWAum6LiHy3rrXD6I453oNm06ecME=,iv:qYXuJpZsj+EE5I91eEQZGICCge2xBngqfkHV6VQDi6U=,tag:WpYVC4Y5KQJDzErQRMaViA==,type:str]
sops:
    age:
        - recipient: age1gy4mys83v95r5cdgp2axgv0ma2yk4xhtxesdwjjfljtmxlclh94s896uy8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEdzVUeGRkelJtRGNUZWVG
            RUNOcnVSckl6RXRPeFBKOTlBWFJxZEFLb0drClovcjVLSkF0Y1VQaU1hSTNQRlJO
            NFNaTjlBZWowZ3FUelVYUWhKQlNXYW8KLS0tIDMyNlZhMDUzUmY5bHpiSjlZaUQ2
            a1pybEozV2dpN2kzTFJGdElQUENCc2sKKT15eNg4gO4KaRKBILo1V/sLOlarWG6l
            PH19gDdfB/U7ftb+vPRqXl7l0ARBAwukP/VXNOTyJ3f2qaOn3EKAUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-28T08:22:51Z"
    mac: ENC[AES256_GCM,data:c1vCS1ouAv34/dTcisNkeNMB/H7WDexjoXYBFyksH4w5d+eyW4bDyo90WEAIX6vmrRx+yL+HoICCiMi8luy9aZZAXxMgaJvwvOuBIg3VcbNwBpNcAjx/A5Uxg4kN7ZXQ3V/6PS3Ziewf7LdUr78/ww+ju4Ke6J0rPHRZHTzqXh4=,iv:j4DpGdDMsFsdUzt+phCkUraTBCKlVnkwTjmGnBe5R2w=,tag:rGtSOgdxMpj9hLtRGMgPzg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
